[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "pnpm install && pnpm run build"

[build.environment]
  # Use Node.js 18 for compatibility
  NODE_VERSION = "18"
  
  # Enable pnpm
  NPM_FLAGS = "--version"
  PNPM_VERSION = "8.15.6"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable HTTPS redirect
[[redirects]]
  from = "http://electronics-inventory-ai.netlify.app/*"
  to = "https://electronics-inventory-ai.netlify.app/:splat"
  status = 301
  force = true

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# Functions (if needed in future)
[functions]
  directory = "netlify/functions"
